# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A. Grant Schissler, Statistician
email: aschissler at unr dot edu
description: >- # this means to ignore newlines until "baseurl:"
  You've found my homepage. I'm an Assistant Professor of Statistics in the Department of Mathematics & Statistics at the University of Nevada, Reno. My research interests are driven by interdisciplinary problems, often in the biomedical domain. Recently, I've help to build statistical informatics tools that allow clinical researchers to interpret molecular data, on the scale of individual patients (aiming to conduct precision medicine). Common themes in the course of these projects include large-scale hypothesis testing, high dimensionality, massively-parallel computing (including GPU acceleration), knowledgebase integration, multivariate statistics, Bayesian analysis, and clustering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://www.grantschissler.com
twitter_username: GSchissler
github_username:  grizant
linkedin_username: grantschissler
google_scholar_username: 1H-SHoMAAAAJ

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
# theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
